### PR TITLE
Don't show about:blank in the URL bar

### PR DESCRIPTION
**Pull request by mbrubeck**

### CODE REVIEW

**Comment by liamzdenek** [comment]
Isn't showing about:blank desired behavior? Why would we hide that the page is intentionally empty from the user?

**Comment by mbrubeck** [comment]
`about:blank` is shown automatically when a new tab loads.  Firefox hides the URL if it is `about:blank`.  (Chrome doesn't, but it does hide `chrome://newtab` which serves a similar purpose in Chrome.)

**Comment by mbrubeck** [comment]
To clarify, the goal for this change is to have an empty URL bar when a new tab is created.  We could do that by hiding `about:blank` like in Firefox, or by using some other special URL for new tabs and hiding that, like Chrome.

**Comment by liamzdenek** [comment]
I understand. :+1:

**Pull request merged**
